// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDak6y6lasZ3mWWxH6zilpFR_54dX-zI18',
    appId: '1:416750482548:web:dfbf5138c7740f322f0d21',
    messagingSenderId: '416750482548',
    projectId: 'fire-base-app-db3f1',
    authDomain: 'fire-base-app-db3f1.firebaseapp.com',
    storageBucket: 'fire-base-app-db3f1.firebasestorage.app',
    measurementId: 'G-0940RNQZHP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAniKDZt8ozLtL4JgsvUcPnHuMBeiAd5ts',
    appId: '1:416750482548:android:1b8c0e822594cfd12f0d21',
    messagingSenderId: '416750482548',
    projectId: 'fire-base-app-db3f1',
    storageBucket: 'fire-base-app-db3f1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA12WQIseHc_3skSgQ5o_dJXijXANujxnU',
    appId: '1:416750482548:ios:955ded554c119e522f0d21',
    messagingSenderId: '416750482548',
    projectId: 'fire-base-app-db3f1',
    storageBucket: 'fire-base-app-db3f1.firebasestorage.app',
    iosBundleId: 'com.example.learningFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA12WQIseHc_3skSgQ5o_dJXijXANujxnU',
    appId: '1:416750482548:ios:955ded554c119e522f0d21',
    messagingSenderId: '416750482548',
    projectId: 'fire-base-app-db3f1',
    storageBucket: 'fire-base-app-db3f1.firebasestorage.app',
    iosBundleId: 'com.example.learningFirebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDak6y6lasZ3mWWxH6zilpFR_54dX-zI18',
    appId: '1:416750482548:web:ea1f8dc97e989a0d2f0d21',
    messagingSenderId: '416750482548',
    projectId: 'fire-base-app-db3f1',
    authDomain: 'fire-base-app-db3f1.firebaseapp.com',
    storageBucket: 'fire-base-app-db3f1.firebasestorage.app',
    measurementId: 'G-VQ57837J4K',
  );
}
